### ISSUE TITLE
Does not work if settings files have BOM

### ISSUE THREAD

**Issue by andgineer** [andgineer/docker-amazon-dash-button-hack#4]
Traceback (most recent call last):
File "amazon_dash.py", line 72, in <module>
main()
File "amazon_dash.py", line 66, in main
settings = load_settings()
File "amazon_dash.py", line 32, in load_settings
return json.loads(settings_file.read())
File "/usr/lib/python3.5/json/__init__.py", line 315, in loads
s, 0)
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by andgineer** [comment]
https://github.com/masterandrey/docker-amazon-dash-button-hack/commit/07b2cf057839178942a15043fd8847f3108a1c59
