### ISSUE TITLE
Simplified fork error

### ISSUE THREAD

**Issue by CoreyCole** [andgineer/docker-amazon-dash-button-hack#5]
I'm working on a simplified fork [here](https://github.com/CoreyCole/docker-amazon-dash-button-hack) where I'm trying to make a simple http request on button press. I was able to get it working with a fresh clone of your repo, but once I moved to my own docker image something has gone wrong. 
```
docker run --rm --net host -it --name amazon_dash coreyleoc/docker-amazon-dash-button-hack
```
```
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
loading buttons
amazon_dash started, loaded 1 buttons
Traceback (most recent call last):
  File "wifi-sniff.py", line 51, in <module>
    main()
  File "wifi-sniff.py", line 48, in main
    sniff(prn=arp_handler, filter="arp", store=0)
  File "/usr/lib/python3.5/site-packages/scapy/sendrecv.py", line 599, in sniff
    r = prn(p)
  File "wifi-sniff.py", line 32, in arp_handler
    if pkt.haslayer(ARP):
NameError: name 'ARP' is not defined
```
I'm still using your Dockerfile with your `docker-python-base`. I know pip is installing things correctly because when I open up bash in my docker I can call python and import scapy.all and such. Any advice? I'm very new to docker. Thanks~

**Comment by CoreyCole** [comment]
It is because I changed
```
from scapy.all import *
```
to
```
from scapy.all import sniff
```
